//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.Validate.Services.WSStatusServicoCTe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", ConfigurationName="WSStatusServicoCTe.CteStatusServicoSoap12")]
    public interface CteStatusServicoSoap12 {
        
        // CODEGEN: Generating message contract since the operation cteStatusServicoCT is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico/cteStatusServicoCT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PS.Validate.Services.WSStatusServicoCTe.cteStatusServicoCTResponse cteStatusServicoCT(PS.Validate.Services.WSStatusServicoCTe.cteStatusServicoCTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico")]
    public partial class cteCabecMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cUFField;
        
        private string versaoDadosField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
                this.RaisePropertyChanged("cUF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
                this.RaisePropertyChanged("versaoDados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cteStatusServicoCTRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico")]
        public PS.Validate.Services.WSStatusServicoCTe.cteCabecMsg cteCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", Order=0)]
        public System.Xml.XmlNode cteDadosMsg;
        
        public cteStatusServicoCTRequest() {
        }
        
        public cteStatusServicoCTRequest(PS.Validate.Services.WSStatusServicoCTe.cteCabecMsg cteCabecMsg, System.Xml.XmlNode cteDadosMsg) {
            this.cteCabecMsg = cteCabecMsg;
            this.cteDadosMsg = cteDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cteStatusServicoCTResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico")]
        public PS.Validate.Services.WSStatusServicoCTe.cteCabecMsg cteCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", Order=0)]
        public System.Xml.XmlNode cteStatusServicoCTResult;
        
        public cteStatusServicoCTResponse() {
        }
        
        public cteStatusServicoCTResponse(PS.Validate.Services.WSStatusServicoCTe.cteCabecMsg cteCabecMsg, System.Xml.XmlNode cteStatusServicoCTResult) {
            this.cteCabecMsg = cteCabecMsg;
            this.cteStatusServicoCTResult = cteStatusServicoCTResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CteStatusServicoSoap12Channel : PS.Validate.Services.WSStatusServicoCTe.CteStatusServicoSoap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CteStatusServicoSoap12Client : System.ServiceModel.ClientBase<PS.Validate.Services.WSStatusServicoCTe.CteStatusServicoSoap12>, PS.Validate.Services.WSStatusServicoCTe.CteStatusServicoSoap12 {
        
        public CteStatusServicoSoap12Client() {
        }
        
        public CteStatusServicoSoap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CteStatusServicoSoap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CteStatusServicoSoap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CteStatusServicoSoap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PS.Validate.Services.WSStatusServicoCTe.cteStatusServicoCTResponse PS.Validate.Services.WSStatusServicoCTe.CteStatusServicoSoap12.cteStatusServicoCT(PS.Validate.Services.WSStatusServicoCTe.cteStatusServicoCTRequest request) {
            return base.Channel.cteStatusServicoCT(request);
        }
        
        public System.Xml.XmlNode cteStatusServicoCT(ref PS.Validate.Services.WSStatusServicoCTe.cteCabecMsg cteCabecMsg, System.Xml.XmlNode cteDadosMsg) {
            PS.Validate.Services.WSStatusServicoCTe.cteStatusServicoCTRequest inValue = new PS.Validate.Services.WSStatusServicoCTe.cteStatusServicoCTRequest();
            inValue.cteCabecMsg = cteCabecMsg;
            inValue.cteDadosMsg = cteDadosMsg;
            PS.Validate.Services.WSStatusServicoCTe.cteStatusServicoCTResponse retVal = ((PS.Validate.Services.WSStatusServicoCTe.CteStatusServicoSoap12)(this)).cteStatusServicoCT(inValue);
            cteCabecMsg = retVal.cteCabecMsg;
            return retVal.cteStatusServicoCTResult;
        }
    }
}
