using System;
using System.Collections.Generic;
using System.Text;

namespace PS.Glb
{
    public class PSPartTipOperSerieData : PS.Lib.WinForms.PSPartData
    {
        public override string ReadViewLookup()
        {
            return @"SELECT CODEMPRESA, CODTIPOPER, CODSERIE, CODFILIAL,
(SELECT DESCRICAO FROM VSERIE WHERE CODEMPRESA = VTIPOPERSERIE.CODEMPRESA AND CODSERIE = VTIPOPERSERIE.CODSERIE AND CODFILIAL = VTIPOPERSERIE.CODFILIAL) DESCRICAO
FROM VTIPOPERSERIE WHERE ";
        }

        public override string ReadView()
        {
            return @"SELECT CODEMPRESA, CODTIPOPER, CODSERIE, CODFILIAL, PRINCIPAL,
(SELECT DESCRICAO FROM VSERIE WHERE CODEMPRESA = VTIPOPERSERIE.CODEMPRESA AND CODSERIE = VTIPOPERSERIE.CODSERIE AND CODFILIAL = VTIPOPERSERIE.CODFILIAL) DESCRICAO
FROM VTIPOPERSERIE WHERE ";
        }
    }
}
