using System;
using System.Collections.Generic;
using System.Text;

namespace PS.Glb
{
    public class PSPartRegraICMSData : PS.Lib.WinForms.PSPartData
    {
        public override string ReadView()
        {
            return @"SELECT CODEMPRESA,
IDREGRA,
DESCRICAO,
CONVERT(BIT, ATIVO) ATIVO,
CODCST,
ALIQUOTA,
REDUCAOBASEICMS,
DIFERENCIALALIQUOTA,
CONSIDERAREDUCAOCALCULOPROPRIO,
PERCICMSUFDEST,
PERCFCP,
DESCONTOST,
DESPESAST,
FRETEST,
REDUCAOBCST,
SEGUROST,
SELECAOMVAST,
UTILIZAST,
DESCONTOICMS,
DESPESAIMCS,
FRETEIMCS,
IPIICMS,
SEGUROICMS,
TIPOTRIBUTACAO,
CONVERT(BIT, CREDITOICMS) CREDITOICMS
FROM VREGRAICMS WHERE";
        }
    }
}
