using System;
using System.Collections.Generic;
using System.Text;

namespace PS.Glb
{
    public class PSPartFilialData : PS.Lib.WinForms.PSPartData
    {
        public override string ReadView()
        {
            return @"SELECT CODEMPRESA,
CODFILIAL,
NOME,
NOMEFANTASIA,
CGCCPF,
CEP,
CODTIPORUA,
RUA,
NUMERO,
COMPLEMENTO,
CODTIPOBAIRRO,
BAIRRO,
CODCIDADE,
(SELECT NOME FROM GCIDADE WHERE CODETD = GFILIAL.CODETD AND CODCIDADE = GFILIAL.CODCIDADE) CCIDADE,
CODETD,
CODPAIS,
TELEFONE,
EMAIL,
INSCRICAOESTADUAL,
INSCRICAOMUNICIPAL,
CODREGIMETRIBUTARIO,
WEBSITE,
PCREDSN,
USASEGUNDONUMERO,
SEGUNDONUMERO,
QTDSEGUNDONUMERO,
SEQSEGUNDONUMERO,
IDENTIFICACAO
FROM GFILIAL WHERE ";
        }
    }
}
