using System;
using System.Collections.Generic;
using System.Text;

namespace PS.Glb
{
    public class PSPartTransportadoraData: PS.Lib.WinForms.PSPartData
    {
        public override string ReadView()
        {
            return @"SELECT CODEMPRESA,
CODTRANSPORTADORA,
NOME,
NOMEFANTASIA,
CGCCPF,
CEP,
CODTIPORUA,
RUA,
NUMERO,
COMPLEMENTO,
CODTIPOBAIRRO,
BAIRRO,
CODCIDADE,
(SELECT NOME FROM GCIDADE WHERE CODETD = VTRANSPORTADORA.CODETD AND CODCIDADE = VTRANSPORTADORA.CODCIDADE) CCIDADE,
CODETD,
CODPAIS,
FISICOJURIDICO,
INSCRICAOESTADUAL,
CONVERT(BIT, ATIVO) ATIVO,
TELEFONE,
TELCELULAR,
TELFAX,
CONTATO,
HOMEPAGE,
EMAIL, 
PIS
FROM VTRANSPORTADORA WHERE ";
        }
    }
}
