using System;
using System.Collections.Generic;
using System.Text;
using PS.Lib;

namespace PS.Glb
{
    public class PSPartTipOper : PS.Lib.WinForms.PSPartGridView
    {
        public PSPartTipOper()
        {
            this.TableName = "GTIPOPER";
            this.Keys = new string[] { "CODEMPRESA", "CODTIPOPER" };
            this.FormEditName = "PSPartTipOperEdit";
            this.PSPartData = new PSPartTipOperData();

            this.DefaultFilter.Add(new PS.Lib.PSFilter("CODEMPRESA", PS.Lib.Contexto.Session.Empresa.CodEmpresa));
            this.DefaultFilterLookup.Add(new PS.Lib.PSFilter("CODEMPRESA", PS.Lib.Contexto.Session.Empresa.CodEmpresa));

            this.MasterDetail.Add(new PS.Lib.WinForms.MasterDetail(new PS.Glb.PSPartTipOperReport(), "CODEMPRESA", "CODTIPOPER"));
            this.MasterDetail.Add(new PS.Lib.WinForms.MasterDetail(new PS.Glb.PSPartTipOperSerie(), "CODEMPRESA", "CODTIPOPER"));
            this.MasterDetail.Add(new PS.Lib.WinForms.MasterDetail(new PS.Glb.PSPartTipOperFat(), "CODEMPRESA", "CODTIPOPER"));
            this.MasterDetail.Add(new PS.Lib.WinForms.MasterDetail(new PS.Glb.PSPartTipOperTributo(), "CODEMPRESA", "CODTIPOPER"));
            this.MasterDetail.Add(new PS.Lib.WinForms.MasterDetail(new PS.Glb.PSPartTipOperMensagem(), "CODEMPRESA", "CODTIPOPER"));

            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USANUMEROSEQ", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("ULTIMONUMERO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAABATRANSP", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAABAOBSERV", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAABATRIBUTOS", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("GERAFINANCEIRO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("GERATRIBUTOS", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("VLUNITARIOEDITA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODTIPDOC", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODMOEDA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("OPERESTOQUE", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("OPERSERIE", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("SERIEDEFAULT", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("LOCAL1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("LOCAL2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOOBJETO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOCONDPGTO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODCONDICAOPADRAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOOPERADOR", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODOPERADORPADRAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODCONTA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("ULTIMONIVEL", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TIPENTSAI", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODCLIFOR", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODCLIFORPADRAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODFORMA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODFORMAPADRAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACONTA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODCONTAPADRAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USANATUREZA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAOPERACAONFE", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACODREPRE", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TIPOPAGREC", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CRIAROPFAT", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("SERIELIVRE", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CLIFORAMB", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAVALORBRUTO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAVALORLIQUIDO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("PRODSERV", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAVLUNITARIO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAPRDESCONTO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAVLDESCONTO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAVLTOTALITEM", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USADATAEMISSAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USADATAENTREGA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USADATAENTSAI", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODFORMULAVALORBRUTO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODFORMULAVALORLIQUIDO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOLIVRE1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOLIVRE2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOLIVRE3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOLIVRE4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOLIVRE5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOLIVRE6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOLIVRE1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOLIVRE2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOLIVRE3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOLIVRE4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOLIVRE5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOLIVRE6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USADATAEXTRA1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USADATAEXTRA2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USADATAEXTRA3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USADATAEXTRA4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USADATAEXTRA5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USADATAEXTRA6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTODATAEXTRA1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTODATAEXTRA2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTODATAEXTRA3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTODATAEXTRA4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTODATAEXTRA5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTODATAEXTRA6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOVALOR1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOVALOR2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOVALOR3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOVALOR4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOVALOR5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACAMPOVALOR6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOVALOR1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOVALOR2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOVALOR3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOVALOR4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOVALOR5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOCAMPOVALOR6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOLIVRE1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOLIVRE2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOLIVRE3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOLIVRE4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOLIVRE5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOLIVRE6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOLIVRE1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOLIVRE2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOLIVRE3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOLIVRE4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOLIVRE5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOLIVRE6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMDATAEXTRA1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMDATAEXTRA2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMDATAEXTRA3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMDATAEXTRA4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMDATAEXTRA5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMDATAEXTRA6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMDATAEXTRA1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMDATAEXTRA2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMDATAEXTRA3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMDATAEXTRA4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMDATAEXTRA5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMDATAEXTRA6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOVALOR1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOVALOR2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOVALOR3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOVALOR4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOVALOR5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAITEMCAMPOVALOR6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOVALOR1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOVALOR2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOVALOR3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOVALOR4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOVALOR5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOITEMCAMPOVALOR6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("VLUNITARIOEM", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USARATEIOCC", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USARATEIODP", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USARATEIOCCITEM", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USARATEIODPITEM", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOLIVRE1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOLIVRE2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOLIVRE3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOLIVRE4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOLIVRE5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOLIVRE6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIADATAEXTRA1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIADATAEXTRA2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIADATAEXTRA3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIADATAEXTRA4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIADATAEXTRA5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIADATAEXTRA6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOVALOR1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOVALOR2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOVALOR3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOVALOR4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOVALOR5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIACAMPOVALOR6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOLIVRE1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOLIVRE2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOLIVRE3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOLIVRE4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOLIVRE5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOLIVRE6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMDATAEXTRA1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMDATAEXTRA2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMDATAEXTRA3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMDATAEXTRA4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMDATAEXTRA5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMDATAEXTRA6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOVALOR1", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOVALOR2", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOVALOR3", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOVALOR4", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOVALOR5", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("COPIAITEMCAMPOVALOR6", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TIPOPER", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("UNDMEDPADRAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODFORMULAVALIDAOPERACAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODFORMULAVALIDAOPERITEM", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("GERAORDEMPRODUCAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODFILIALDEFUALT", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("LOCAL1DEFAULT", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODNATDENTRO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODNATFORA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TIPOIMPRESSAODANFE", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("MODDOCFISCAL", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("TEXTOPRODNFE", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("FINEMISSAONFE", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAVALORFRETE", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAVALORDESCONTO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAVALORDESPESA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAVALORSEGURO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACODNATUREZAORCAMENTO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USACODCCUSTO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("MASKNUMEROSEQ", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("CODREPREPADRAO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("PERMITEFATURAMENTOPARCIAL", false));
            //this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("VERIFICAVENCIMENTO", false));
            //this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("QTDDIASVENCIDOS", false));
            //this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("IDGRUPOREL", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("AUTOSELECAONATUREZA", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USANUMEROORIGEM", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USALOTEPRODUTO", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("USAABARELACCTRC", false));
            this.DefaultCustomDataColumns.Add(new PS.Lib.CustomDataColumn("DESCNATOP", false));

            this.SecurityID = "PSPartTipOper";
            this.ModuleID = "PG";
        }

        public override List<DataField> GetTableColumn()
        {
            List<DataField> objArr = new List<DataField>();

            objArr.Add(new DataField("TIPOPER", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TIPENTSAI", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("DESCRICAO", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("CODTIPOPER", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("CODFORMULAVALIDAOPERACAO", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("SERIELIVRE", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("SERIEDEFAULT", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("OPERSERIE", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODTIPOPERREF", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("MASKNUMEROSEQ", null, typeof(PS.Lib.WinForms.PSMoedaBox)));
            objArr.Add(new DataField("USANUMEROSEQ", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("ULTIMONUMERO", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("CLIFORAMB", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODCLIFORPADRAO", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("CODCLIFOR", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USADATAEMISSAO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USADATAENTREGA", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USADATAENTSAI", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAVALORLIQUIDO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODFORMULAVALORLIQUIDO", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("USAVALORBRUTO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODFORMULAVALORBRUTO", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("COPIACAMPOLIVRE6", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOLIVRE5", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOLIVRE4", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOLIVRE3", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOLIVRE2", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOLIVRE1", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("TEXTOCAMPOLIVRE6", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOCAMPOLIVRE5", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOCAMPOLIVRE4", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOCAMPOLIVRE3", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOCAMPOLIVRE2", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOCAMPOLIVRE1", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USACAMPOLIVRE6", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACAMPOLIVRE5", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACAMPOLIVRE4", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACAMPOLIVRE3", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACAMPOLIVRE2", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACAMPOLIVRE1", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("COPIADATAEXTRA6", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIADATAEXTRA5", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIADATAEXTRA4", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIADATAEXTRA3", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIADATAEXTRA2", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIADATAEXTRA1", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("TEXTODATAEXTRA6", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTODATAEXTRA5", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTODATAEXTRA4", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTODATAEXTRA3", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTODATAEXTRA2", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTODATAEXTRA1", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USADATAEXTRA6", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USADATAEXTRA5", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USADATAEXTRA4", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USADATAEXTRA3", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USADATAEXTRA2", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USADATAEXTRA1", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("COPIACAMPOVALOR6", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOVALOR5", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOVALOR4", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOVALOR3", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOVALOR2", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIACAMPOVALOR1", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("TEXTOCAMPOVALOR6", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USACAMPOVALOR6", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOCAMPOVALOR5", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USACAMPOVALOR5", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOCAMPOVALOR4", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USACAMPOVALOR4", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOCAMPOVALOR3", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USACAMPOVALOR3", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOCAMPOVALOR2", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USACAMPOVALOR2", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOCAMPOVALOR1", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USACAMPOVALOR1", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAABAOBSERV", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("CRIAROPFAT", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("ULTIMONIVEL", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("USAABATRIBUTOS", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("GERATRIBUTOS", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("CODCONTAPADRAO", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("USACONTA", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODFORMAPADRAO", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("CODCONDICAOPADRAO", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("CODFORMA", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACAMPOCONDPGTO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACAMPOOBJETO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACODREPRE", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODOPERADORPADRAO", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("USACAMPOOPERADOR", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("OPERESTOQUE", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("LOCAL1", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("LOCAL2", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TIPOPAGREC", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODCONTA", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("GERAFINANCEIRO", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("GERABOLETO", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("CODTIPDOC", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("CODMOEDA", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("USAABATRANSP", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("USAOPERACAONFE", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USARATEIODPITEM", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("USARATEIOCCITEM", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("USARATEIODP", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("USARATEIOCC", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("GERAORDEMPRODUCAO", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("CODFORMULAVALIDAOPERITEM", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("UNDMEDPADRAO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("PRODSERV", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("VLUNITARIOEM", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAVLUNITARIO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAPRDESCONTO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAVLDESCONTO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAVLTOTALITEM", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODFORMULANATUREZA", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("USANATUREZA", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODNATDENTRO", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("CODNATFORA", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("COPIAITEMCAMPOLIVRE6", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOLIVRE5", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOLIVRE4", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOLIVRE3", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOLIVRE2", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOLIVRE1", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOLIVRE6", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMCAMPOLIVRE6", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOLIVRE5", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMCAMPOLIVRE5", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOLIVRE4", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMCAMPOLIVRE4", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOLIVRE3", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMCAMPOLIVRE3", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOLIVRE2", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMCAMPOLIVRE2", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOLIVRE1", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMCAMPOLIVRE1", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("COPIAITEMDATAEXTRA6", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMDATAEXTRA5", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMDATAEXTRA4", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMDATAEXTRA3", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMDATAEXTRA2", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMDATAEXTRA1", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("TEXTOITEMDATAEXTRA6", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMDATAEXTRA6", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMDATAEXTRA5", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMDATAEXTRA5", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMDATAEXTRA4", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMDATAEXTRA4", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMDATAEXTRA3", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMDATAEXTRA3", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMDATAEXTRA2", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMDATAEXTRA2", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOITEMDATAEXTRA1", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMDATAEXTRA1", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOVALOR6", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOVALOR5", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOVALOR4", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOVALOR3", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOVALOR2", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("COPIAITEMCAMPOVALOR1", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOVALOR6", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOVALOR5", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOVALOR4", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOVALOR3", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOVALOR2", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("TEXTOITEMCAMPOVALOR1", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("PERMITEFATURAMENTOPARCIAL", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("USAITEMCAMPOVALOR6", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAITEMCAMPOVALOR5", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAITEMCAMPOVALOR4", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAITEMCAMPOVALOR3", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAITEMCAMPOVALOR2", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAITEMCAMPOVALOR1", null, typeof(PS.Lib.WinForms.PSComboBox)));            
            objArr.Add(new DataField("CODEMPRESA", null, typeof(PS.Lib.WinForms.PSTextoBox)));
            objArr.Add(new DataField("CODFILIALDEFUALT", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("LOCAL1DEFAULT", null, typeof(PS.Lib.WinForms.PSLookup)));
            objArr.Add(new DataField("TIPOIMPRESSAODANFE", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("MODDOCFISCAL", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("TEXTOPRODNFE", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("FINEMISSAONFE", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAVALORFRETE", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAVALORDESCONTO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAVALORDESPESA", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USAVALORSEGURO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACODNATUREZAORCAMENTO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("USACODCCUSTO", null, typeof(PS.Lib.WinForms.PSComboBox)));
            objArr.Add(new DataField("CODREPREPADRAO", null, typeof(PS.Lib.WinForms.PSLookup)));
            //objArr.Add(new DataField("VERIFICAVENCIMENTO", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("AUTOSELECAONATUREZA", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("USANUMEROORIGEM", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("USALOTEPRODUTO", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("USAABARELACCTRC", null, typeof(PS.Lib.WinForms.PSCheckBox)));
            objArr.Add(new DataField("DESCNATOP", null, typeof(PS.Lib.WinForms.PSTextoBox)));

            return objArr;
        }
    }
}
